name: Deploy on merge to main/master

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Ajusta esta versión según tus necesidades

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to server
      run: |
        scp -o StrictHostKeyChecking=no -r -i private_key.pem dist/* ec2-user@44.211.52.12:/var/www/html/fe-octavo/
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@44.211.52.12 "sudo chown -R ec2-user:ec2-user /var/www/html/fe-octavo/ && sudo systemctl restart httpd && sudo systemctl status httpd"
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
