name: Deploy on merge to main/master

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Ajusta esta versión según tus necesidades

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to server
      run: |
        scp -r dist/* ec2-user@44.211.52.12/var/www/html/fe-octavo/
        ssh ec2-user@44.211.52.12 "sudo systemctl restart httpd && sudo systemctl status httpd"
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}


